// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCnmieJUzrjqDsFxDuzLP1iRIPqJlN_uqo',
    appId: '1:1020251192780:web:05c8d1eb1145c02b6e7169',
    messagingSenderId: '1020251192780',
    projectId: 'vnotes-app-12345',
    authDomain: 'vnotes-app-12345.firebaseapp.com',
    storageBucket: 'vnotes-app-12345.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyChTWFWfHa3dFZjJ2WGDxpKNt_tK7YQlpU',
    appId: '1:1020251192780:android:25936d04c40d25bd6e7169',
    messagingSenderId: '1020251192780',
    projectId: 'vnotes-app-12345',
    storageBucket: 'vnotes-app-12345.firebasestorage.app',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCnmieJUzrjqDsFxDuzLP1iRIPqJlN_uqo',
    appId: '1:1020251192780:web:257223c7602bc2e96e7169',
    messagingSenderId: '1020251192780',
    projectId: 'vnotes-app-12345',
    authDomain: 'vnotes-app-12345.firebaseapp.com',
    storageBucket: 'vnotes-app-12345.firebasestorage.app',
  );
}
